# Generated by Django 5.0.7 on 2024-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='qty',
        ),
    ]
