# Generated by Django 5.0.7 on 2024-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
